######################################################################
# Automatically generated by qmake (3.0) qui jun 4 22:40:35 2015
######################################################################

TEMPLATE = app
TARGET = comparer
INCLUDEPATH += . src

# Input
HEADERS += src/Comparer.h src/FileDesc.h src/Filesystem.h
SOURCES += src/Comparer.cpp src/FileDesc.cpp src/Filesystem.cpp src/main.cpp

